import { Box, Typography, Flex } from '@strapi/design-system';
import { RouteItemProps } from '../../types';
import { ModalContext } from '../../contexts';
import { useContext, forwardRef, useEffect, useMemo } from 'react';
import { Drag } from '@strapi/icons';
import RouteItemMenu from './RouteItemMenu';
import RouteItemStatus from './RouteItemStatus';
import RouteItemIcon from './RouteItemIcon';
import RouteItemBadge from './RouteItemBadge';
import { findParentNavItem } from '../../utils';
import { NestedNavItem } from '../../../../types';

export const RouteItem = forwardRef<HTMLDivElement, RouteItemProps>(({
  item,
  initialItem,
  setActionItemParent,
  setActionItem,
  setNavigationItems,
  ghost,
  depth,
  maxDepth,
  style,
  wrapperRef,
  handleProps,
  navigationItems,
}: RouteItemProps, ref) => {
  const { setModalType } = useContext(ModalContext);

  const parentNavItem = useMemo(() => findParentNavItem({
    navigationItems,
    targetItem: item,
    onlyInternalItems: true,
  }), [navigationItems, item]);

  const hasStructureChanges = useMemo(() => {
    if (!initialItem) return false;

    return initialItem.order !== item.order
      || initialItem.depth !== item.depth;
  }, [initialItem, item.order, item.depth]);

  const isUpdated = item.clientModifications?.type === 'update' || hasStructureChanges;

  const itemPath = useMemo(() => {
    if (!item.route) return ''
    if (item.route.type !== 'internal') return item.route.path

    const parentPath = parentNavItem ? `${(parentNavItem.clientModifications?.path || parentNavItem.route.path)}/` : '';
    const itemSlug = item.clientModifications?.slug || item.route.slug;
    return `${parentPath}${itemSlug}`;
  }, [item, parentNavItem, isUpdated]);

  const updateNavItem = (navItems: NestedNavItem[] | undefined): NestedNavItem[] | undefined => {
    if (!navItems) return navItems;
    return navItems.map(navItem => {
      if (navItem.documentId === item.documentId) {
        if (navItem.clientModifications?.path === itemPath) {
          return navItem;
        }

        return {
          ...navItem,
          clientModifications: navItem.clientModifications
            ? {
                ...navItem.clientModifications,
                path: itemPath,
              }
            : {
                type: 'update',
                path: itemPath,
                autoGenerated: true,
              },
        };
      }
      return navItem;
    });
  };

  const removeNavItemModifications = (navItems: NestedNavItem[] | undefined): NestedNavItem[] | undefined => {
    if (!navItems) return navItems;
    return navItems.map(navItem => {
      if (navItem.documentId === item.documentId) {
        const { clientModifications, ...rest } = navItem;
        return rest;
      }
      return navItem;
    });
  };

  useEffect(() => {
    if (item.route?.type !== 'internal') return;

    const shouldSyncPath = item.clientModifications?.path !== itemPath
      && (item.clientModifications?.type === 'update' || itemPath !== item.route.path);

    if (shouldSyncPath) {
      setNavigationItems(updateNavItem);
    }
  }, [itemPath, item.documentId, item.route?.type, item.route?.path, item.clientModifications?.type, item.clientModifications?.path, setNavigationItems]);

  useEffect(() => {
    if (item.route?.type !== 'internal') return;

    const canBeRemoved = item.clientModifications?.autoGenerated
      && item.route.path === itemPath
      && !hasStructureChanges;

    if (canBeRemoved) {
      setNavigationItems(removeNavItemModifications);
    }
  }, [itemPath, item.documentId, item.route?.type, item.route?.path, item.clientModifications?.autoGenerated, hasStructureChanges, setNavigationItems]);

  const handleAddChildren = () => {
    setActionItemParent(item)
    setModalType('ItemCreate')
  }

  const handleEdit = () => {
    setActionItem(item)

    let newModal = 'ItemEdit'
    if (item.route.type === 'external') newModal = 'ExternalEdit'
    if (item.route.type === 'wrapper') newModal = 'WrapperEdit'

    setModalType(newModal)
  }

  const handleDelete = () => {
    setActionItem(item)
    setModalType('ItemDelete')
  }

  const handleRestore = () => {
    setNavigationItems(navItems =>
      navItems?.map(navItem => {
        if (navItem.documentId === item.documentId) {
          const { clientModifications: _, ...rest } = navItem;
          return navItem.initialClientModifications
            ? { ...rest, clientModifications: navItem.initialClientModifications }
            : rest;
        }
        return navItem;
      })
    );
  }

  const elStyle = {
    marginLeft: depth !== undefined ? depth * 48 : 0,
    opacity: (ghost || item.clientModifications?.type === 'delete') ? 0.5 : 1,
    ...style,
  }

  if (!item || !item.route) return null

  return (
    <Box
      ref={wrapperRef}
      style={elStyle}
    >
      <Box
        background="neutral0"
        borderColor={item.clientModifications?.type === 'delete' ? 'danger500' : 'neutral150'}
        hasRadius
        paddingBottom={4}
        paddingLeft={4}
        paddingRight={4}
        paddingTop={4}
        shadow="tableShadow"
        ref={ref}
      >
        <Flex justifyContent="space-between" gap={4}>
          <Flex gap={4}>
            <Drag color="neutral800" {...handleProps}/>
            <Box
              width="1px"
              height="32px"
              background="neutral150"
            />
            <RouteItemIcon type={item.route.type}/>
            <Flex gap={2}>
              <Typography fontWeight="bold">
                {item.clientModifications?.title ? item.clientModifications.title : item.route.title}
              </Typography>
              {itemPath && <Typography textColor="neutral400">
                /{itemPath}
              </Typography>}
            </Flex>
            <RouteItemStatus item={item} isUpdated={hasStructureChanges} />
          </Flex>
          <Flex direction="row" gap={4}>
            <RouteItemBadge item={item} />
            <RouteItemMenu
              item={item}
              depth={depth}
              maxDepth={maxDepth}
              handleEdit={handleEdit}
              handleAddChildren={handleAddChildren}
              handleDelete={handleDelete}
              handleRestore={handleRestore}
            />
          </Flex>
        </Flex>
      </Box>
    </Box>
  )
})
